# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  buildConfiguration: 'Release'
  terraformVersion: '1.9.8'

pool:
  vmImage: ubuntu-latest

# Build
stages:
  - stage: Build
    displayName: 'Build et test'
    jobs:
    - job: 'Build'
      displayName: 'Build application'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/GriftBusiness.Api/GriftBusiness.Api/GriftBusiness.Api.csproj'
          feedsToUse: 'select'
        displayName: 'Restaure les packages'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/GriftBusiness.Api/GriftBusiness.Api/GriftBusiness.Api.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'Génération de la solution'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/GriftBusiness.Api/GriftBusiness.Tests/*Tests.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'Exécution des tests unitaires'

# security
  - stage: SecurityAnalysis
    displayName: 'Security Analysis'
    jobs:
      - job: SecurityScan
        displayName: 'Run security scan'
        steps:
          - script: echo "Running security analysis..."
            displayName: "Security check"

# terraform
  - stage: Terraform 
    displayName: "Build infra with terraform"
    dependsOn:
      - Build
      - SecurityAnalysis
    jobs:
      - job: deployTerraform
        displayName: "deploy infrastructure with terraform"
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

                wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

                echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
                https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
                sudo tee /etc/apt/sources.list.d/hashicorp.list

                sudo apt update

                sudo apt-get install terraform

                terraform init

                terraform plan -var="login=Jinkx" -var="password=zeDevops@!123" -out main.tfplan

                terraform apply main.tfplan
                
              workingDirectory: 'terraform-az-webapp/'
          



        

